# Generated by Django 5.2 on 2025-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='dataCriacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='dataEdicao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
