# Generated by Django 5.2 on 2025-05-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_linguagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linguagem',
            name='biblioteca',
        ),
    ]
