# Generated by Django 5.2 on 2025-05-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_linguagem_biblioteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='exemplo',
            field=models.TextField(max_length=200, verbose_name='exemplo'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='linguagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linguagem'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(max_length=20, verbose_name='tipo'),
        ),
    ]
